### ISSUE TITLE
使用可能なパーツの一覧機能

### ISSUE THREAD

**Issue by tooppoo** [tooppoo/ac6_assemble_tool#13]
指定した絞り込み条件で利用可能なパーツを一覧して、別途表示する

「シュナイダー製パーツのみでプレイ」
「ルビコン系企業のパーツのみでプレイ」
といったプレイを支援する機能として

**Comment by tooppoo** [comment]
パーツデータ、あるいはスキーマからレコードスキーマを生成する？

```ts
type Record<T> {
  key: string
  type: T
  filter: Filter[]
}
```

**Comment by tooppoo** [comment]
UIイメージ

---

一覧
![スクリーンショット 2024-12-03 7 20 26](https://github.com/user-attachments/assets/742a247f-7131-49f8-a666-8c6dbec5c402)

<details>

```html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>パーツ一覧</title>
  <link rel="stylesheet" href="styles.css">
</head>

<body>
  <!-- ヘッダー -->
  <header class="header">
    <h1>パーツ一覧</h1>
    <input type="text" placeholder="検索..." class="search-bar">
  </header>

  <!-- 全体フィルタとソートセクション -->
  <section class="filter-sort-section">
    <button class="filter-button">全体フィルタ▼</button>
    <button class="sort-button">全体ソート▼</button>
    <div class="applied-filters">
      <span>適用中のフィルタ:</span>
      <span class="filter-tag">頭部: 重量 >= 200</span>
      <span class="filter-tag">胴体: 開発企業=ベイラム</span>
      <span class="filter-tag">胴体: 重量 昇順</span>
    </div>
  </section>

  <!-- パーツ一覧セクション -->
  <section class="parts-section">
    <div class="part-category">
      <h2>部位: 頭部</h2>
      <div class="filter-sort-controls">
        <button class="filter-button">頭部フィルタ▼</button>
        <button class="sort-button">頭部ソート▼</button>
      </div>
      <div class="parts-grid">
        <div class="part-card">
          <div class="part-info">
            <p>パーツ1</p>
            <p>重量: 210, 攻撃力: 30</p>
          </div>
          <button class="select-button">選択</button>
        </div>
        <div class="part-card">
          <div class="part-info">
            <p>パーツ2</p>
            <p>重量: 250, 攻撃力: 35</p>
          </div>
          <button class="select-button">選択</button>
        </div>
      </div>
    </div>
    <div class="part-category">
      <h2>部位: 胴体</h2>
      <div class="filter-sort-controls">
        <button class="filter-button">胴体フィルタ▼</button>
        <button class="sort-button">胴体ソート▼</button>
      </div>
      <div class="parts-grid">
        <div class="part-card">
          <div class="part-info">
            <p>パーツ3</p>
            <p>重量: 120, 開発企業: ベイラム</p>
          </div>
          <button class="select-button">選択</button>
        </div>
        <div class="part-card">
          <div class="part-info">
            <p>パーツ4</p>
            <p>重量: 150, 開発企業: ベイラム</p>
          </div>
          <button class="select-button">選択</button>
        </div>
      </div>
    </div>
  </section>

  <!-- 固定アクションバー -->
  <footer class="action-bar">
    <div>
      <p>選択中のパーツ: 頭部: パーツ1, 胴体: パーツ3</p>
      <p>適用中のフィルタ: 頭部: 重量 >= 200, 胴体: 開発企業=ベイラム, 胴体: 重量 昇順</p>
    </div>
    <button class="apply-button">カスタマイズページへ反映</button>
  </footer>
</body>

</html>
```

```css
/* リセット */
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: Arial, sans-serif;
  line-height: 1.5;
}

/* ヘッダー */
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 20px;
  background-color: #f8f8f8;
  border-bottom: 1px solid #ddd;
}

.header h1 {
  font-size: 1.5rem;
}

.search-bar {
  padding: 5px;
  font-size: 1rem;
  width: 50%;
}

/* フィルタとソートセクション */
.filter-sort-section {
  padding: 10px 20px;
  background-color: #fff;
  border-bottom: 1px solid #ddd;
}

.filter-button, .sort-button {
  padding: 5px 10px;
  margin-right: 10px;
  font-size: 1rem;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 3px;
  cursor: pointer;
}

.filter-button:hover, .sort-button:hover {
  background-color: #0056b3;
}

.applied-filters {
  margin-top: 10px;
}

.filter-tag {
  display: inline-block;
  background-color: #e9ecef;
  padding: 5px 10px;
  border-radius: 3px;
  margin-right: 5px;
}

/* パーツ一覧セクション */
.parts-section {
  padding: 20px;
}

.part-category {
  margin-bottom: 20px;
}

.part-category h2 {
  margin-bottom: 10px;
}

.filter-sort-controls {
  margin-bottom: 10px;
}

.parts-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
  gap: 20px;
}

.part-card {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  padding: 15px;
  background-color: #f8f8f8;
  border: 1px solid #ddd;
  border-radius: 5px;
}

.part-info p {
  margin-bottom: 5px;
}

.select-button {
  padding: 5px 10px;
  font-size: 0.9rem;
  background-color: #28a745;
  color: #fff;
  border: none;
  border-radius: 3px;
  cursor: pointer;
}

.select-button:hover {
  background-color: #218838;
}

/* 固定アクションバー */
.action-bar {
  position: fixed;
  bottom: 0;
  width: 100%;
  background-color: #007bff;
  color: #fff;
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 10px 20px;
  flex-wrap: wrap;
}

.apply-button {
  padding: 10px 20px;
  font-size: 1rem;
  background-color: #ffc107;
  color: #000;
  border: none;
  border-radius: 3px;
  cursor: pointer;
}

.apply-button:hover {
  background-color: #e0a800;
}

/* メディアクエリ */
@media (min-width: 768px) {
  .header {
    padding: 15px 40px;
  }

  .filter-sort-section {
    padding: 15px 40px;
  }

  .parts-section {
    padding: 30px 40px;
  }

  .parts-grid {
    grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
  }
}

```

</details>

---

パーツ詳細
![スクリーンショット 2024-12-03 7 35 40](https://github.com/user-attachments/assets/a6ceef65-9f32-4177-9e31-2ace376d648b)
![スクリーンショット 2024-12-03 7 36 21](https://github.com/user-attachments/assets/76fb09b2-817a-42a5-8df3-bdf739332b1e)

<details>

```html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>パーツ一覧</title>
  <link rel="stylesheet" href="card.css">
</head>

<body>
  <script src="./card.js"></script>

  <!-- パーツカード -->
  <div class="part-card">
    <div class="part-info">
      <p>パーツ1</p>
      <p>重量: 210, 攻撃力: 30</p>
    </div>
    <div class="card-actions">
      <button class="select-button">選択</button>
      <button class="details-button" onclick="showDetails('part1')">詳細を見る</button>
    </div>
  </div>

  <!-- モーダル -->
  <div id="modal-part-details" class="modal hidden">
    <div class="modal-content">
      <span class="close-button" onclick="closeDetails()">×</span>
      <h2>パーツ1の詳細情報</h2>
      <p><strong>重量:</strong> 210</p>
      <p><strong>攻撃力:</strong> 30</p>
      <p><strong>開発企業:</strong> ベイラム</p>
      <p><strong>説明:</strong> このパーツは高い防御力を誇ります。</p>
    </div>
  </div>
</body>
```

```css
/* モーダルスタイル */
.modal {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: rgba(0, 0, 0, 0.5);
  display: flex;
  justify-content: center;
  align-items: center;
}

.hidden {
  display: none;
}

.modal-content {
  background: #fff;
  padding: 20px;
  border-radius: 8px;
  width: 80%;
  max-width: 500px;
  position: relative;
}

.close-button {
  position: absolute;
  top: 10px;
  right: 10px;
  font-size: 20px;
  cursor: pointer;
  border: none;
  background: none;
}
```

```js
function showDetails(partId) {
  // モーダル要素を取得して表示
  const modal = document.getElementById('modal-part-details');
  modal.classList.remove('hidden');
}

function closeDetails() {
  // モーダルを非表示
  const modal = document.getElementById('modal-part-details');
  modal.classList.add('hidden');
}
```

</details>
